import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Aside, { MobileMenu } from "@/components/aside";
import Header from "@/components/header";
import RightAside from "@/components/right-aside";

// Load Inter font with CSS variable
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased m-2 lg:m-[40px]`}>
        <div className="flex">
          <div className="flex-none">
            <Aside />
          </div>
          <main className="w-full flex-auto">
            <Header />
            {children}
          </main>
        </div>
        {/* <RightAside /> */}
        <MobileMenu />
      </body>
    </html>
  );
}
